web_adr: "http://adminold.itland.enes.tech/index.php/map"
driver: "chromedriver.exe"
binary_browser_pth: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
sql_data: "table.sql"
pro_comps: {"les": [15, 16, 17, 18, 19, 20]}

